subscribe_specific:
  name: Subscribe
  desciption: "Subscribe a specific user to an event"
  fields:
    targetPerson:
      name: Person(s)
      description: Person that should be subscribed
      required: true
      selector:
        entity:
          multiple: true
          filter:
            - domain: person
    targetEvent:
      name: Event
      description: Event the person(s) should be subscribed to
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription

subscribe_dynamic:
  name: Subscribe
  desciption: "Subscribe user from context to an event"
  fields:
#    targetPerson:
#      selector:
#        template: #"{% if trigger.event is defined %}{{trigger.event.context.user_id}}{%endif %}{% if trigger.to_state is defined %}{{trigger.to_state.context.user_id}}{% endif %}"
    targetEvent:
      name: Event
      description: Event the person(s) should be subscribed to
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription