subscribe:
  name: Subscribe
  desciption: "Subscribe a specific user to an event"
  fields:
    targetPerson:
      name: Person(s)
      description: Person that should be subscribed
      required: true
      selector:
        entity:
          multiple: true
          filter:
            - domain: person
    targetEvent:
      name: Event
      description: Event the person(s) should be subscribed to
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: eventsubscription