user_specific:
  name: Subscribe
  desciption: "Subscribe a specific user to an event"
  fields:
    targetPerson:
      name: Person(s)
      description: Person that should be subscribed
      required: true
      selector:
        entity:
          multiple: true
          filter:
            - domain: person
    targetEvent:
      name: Event
      description: Event the person(s) should be subscribed to
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription
    action:
      name: Action
      description: Action to be done
      required: true
      selector:
        select:
          options:
            - "register"
            - "unregister"
    suppressMessage:
      name: Suppress message
      description: No not send message when subscribing user
      required: true
      selector:
        boolean:
    customMessage:
      name: Custom message
      description: Message to send
      required: false
      selector:
        text:

user_dynamic:
  name: Do dynamic
  desciption: Get user from context
  fields:
    targetEvent:
      name: Event
      description: Event the person(s) should be subscribed to
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription
    action:
      name: Action
      description: Action to be done
      required: true
      selector:
        select:
          options:
            - "register"
            - "unregister"
    suppressMessage:
      name: Suppress message
      description: No not send message when subscribing user
      required: true
      selector:
        boolean:
    customMessage:
      name: Custom message
      description: Message to send
      required: false
      selector:
        text:

reset:
  name: Reset
  desciption: Reset all users subscribed
  fields:
    targetEvent:
      name: Event
      description: Event that should be reset
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription

complete:
  name: Complete
  desciption: Notify all users subscribed
  fields:
    targetEvent:
      name: Event
      description: Event that completed
      required: true
      selector:
        entity:
          multiple: false
          filter:
            - domain: sensor
              integration: eventsubscription
    customMessage:
      name: Custom message
      description: Message to send
      required: false
      selector:
        text: